Add InvalidRefreshToken error
ResultadosDigitais/rdstation-ruby-client pull request #60
Opened 2020-09-24 17:51 UTC by filipenasc

This PR adds a new exception: `RDStation::Error::InvalidRefreshToken`.

This exception is raised in the following cases:

- The app revoked the authorization
- The end-user revoked the authorization
- The refresh token is invalid

## How to test

- Install an app in your RD Station production account
- Open this gem directory and run the console:

```
> gem build rdstation-ruby-client.gemspec
> rake console
```

- In the console, set your credentials up:

```ruby
RDStation.configure do |config|
  config.client_id = CLIENT_ID
  config.client_secret = CLIENT_SECRET
end

refresh_token = MY_REFRESH_TOKEN

rdstation_authentication = RDStation::Authentication.new
```

- Make a request to obtain a new access token:

```ruby
rdstation_authentication.update_access_token(refresh_token)
```

- [ ] The response should include the credentials:

```ruby
{
  "access_token"=> ACCESS_TOKEN,
 "expires_in"=>86400,
 "refresh_token"=>REFRESH_TOKEN
}
```

- Delete the app from your account: https://app.rdstation.com.br/integracoes
- Now, repeat the request for a new access token:
```ruby
rdstation_authentication.update_access_token(refresh_token)
```

- [ ] It should raise a `RDStation::Error::InvalidRefreshToken` error

2020-09-24 19:00 UTC, m3nd3s requested changes

2020-09-24 21:11 UTC, danilodelponte commented on lib/rdstation/error_handler/invalid_refresh_token.rb
> +        errors.select { |error| error['error_type'] == ERROR_CODE }
+1 pro find

2020-09-24 21:12 UTC, danilodelponte commented on Rakefile
> +  exec 'pry -r rdstation-ruby-client -I ./lib'
que é isso?

2020-09-24 22:53 UTC, m3nd3s commented on Rakefile
> +  exec 'pry -r rdstation-ruby-client -I ./lib'
É pra inicializar um “console” com a gema carregada

2020-09-25 12:24 UTC, filipenasc commented on lib/rdstation/error_handler/invalid_refresh_token.rb
> +        errors.select { |error| error['error_type'] == ERROR_CODE }
Boa, não tinha me ligado nisso. Feito!

2020-09-25 12:34 UTC, m3nd3s approved these changes
:v:

2020-09-25 15:38 UTC, rafaelhancke approved these changes
LGTM

2020-09-25 20:10 UTC, merged